# Generated by Django 5.0.6 on 2025-05-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collections',
            name='notes',
            field=models.ManyToManyField(to='Notes.notes'),
        ),
        migrations.AddConstraint(
            model_name='notes',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='No_two_notes_with_the_message'),
        ),
    ]
